services:
   barotrauma:
      image: thijsvanloef/barotrauma-server-docker
      restart: unless-stopped
      container_name: barotrauma-server
      ports:
        - 27015:27015/udp
        - 27016:27016/udp
      environment:
         - S.name=testing
         - S.password=password
         - S.maxplayers=10
         - S.port=27015
         - S.queryport=27016
      volumes:
         - ./barotrauma-test-folder:/barotrauma/